In [3]:
import numpy as np

In [4]:
# creating a 2x2 array
arr = [[1,2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [5]:
# Convert to numpy array
np.array(arr)

array([[1, 2],
       [3, 4]])

In [6]:
import torch

In [7]:
# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[ 1.,  2.],
        [ 3.,  4.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
torch.ones((2,2))

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [10]:
np.random.rand(2, 2)

array([[0.72059141, 0.10950085],
       [0.59768572, 0.18963022]])

In [11]:
torch.rand(2, 2)

tensor([[ 0.8373,  0.8918],
        [ 0.6714,  0.7909]])

In [12]:
#Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [13]:
np.random.rand(2,2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [15]:
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

In [16]:
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

In [18]:
torch.rand(2,2)

tensor([[ 0.4556,  0.6323],
        [ 0.3489,  0.4017]])

Numpy and Torch Bridge

In [20]:
np_array = np.ones((2, 2))

In [21]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [22]:
print(type(np_array))

<class 'numpy.ndarray'>


In [23]:
torch_tensor = torch.from_numpy(np_array)

In [24]:
print(torch_tensor)

tensor([[ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float64)


In [25]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [26]:
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

In [27]:
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[ 1,  1],
        [ 1,  1]])

# Variables
* A variable wraps a Tensor
* Allows accumulation of gradients (talks in the later chapter notes)

In [28]:
import torch
from torch.autograd import Variable

In [29]:
a = Variable(torch.ones(2,2), requires_grad=True)
a

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [30]:
torch.ones(2,2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])